config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users

  resources :requests, only: [:index, :create, :show] do
    resources :comments, only: [:create, :show, :index]

    member do
      put :resolve
    end
  end

  namespace :admin do
    resources :requests, only: [:index] do
      member do
        put :resolve
      end

      collection do
        get :report
      end
    end

    root to: "home#show", via: :get
  end

  root to: "home#show", via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :request

  validates :user, presence: true
  validates :request, presence: true

  def as_json(opts={})
    #TODO: move to a presenter class
    original = super(opts)
    original.merge({
      'created_at' => I18n.l(original['created_at'], format: :short)
    })
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :user, presence: true
  validates :title, presence: true

  include AASM

  aasm column: :state do
    state :opened, initial: true
    state :waiting_user_reply
    state :resolved

    event :resolve do
      transitions to: :resolved
    end
  end

  def as_json(opts={})
    #TODO: move to a presenter class
    original = super(opts)
    original.merge({
      'updated_at' => I18n.l(original['updated_at'], format: :short)
    })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :requests

  validates :name, presence: true
  validates :email, presence: true

  def admin?
    Array(roles).include?(ADMIN_ROLE)
  end

  private

  ADMIN_ROLE = 'admin'
  private_constant :ADMIN_ROLE

end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_action :verify_admin_role!

    layout 'admin'

    private

    def verify_admin_role!
      unless current_user.admin?
        flash[:error] = t('admin.login_not_authorized')
        sign_out(current_user)
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < BaseController
    def show
    end
  end
end

app/controllers/admin/requests_controller.rb
module Admin
  class RequestsController < BaseController
    respond_to :json

    def index
      requests =
        Request.all
               .includes(:user)
               .where.not(state: 'resolved')
               .order(:updated_at)

      render json: requests.to_json(include: :user)
    end

    def resolve
      request = Request.find(params[:id])
      request.resolve!

      render json: request.to_json(include: :user)
    end

    def report
      @date = I18n.l(DateTime.now - 1.month, format: :report_file_name)
      @initial_date = DateTime.now.beginning_of_month - 1.month
      @final_date = DateTime.now.beginning_of_month
      @closed_requests = Request.resolved.where(
        updated_at: @initial_date..@final_date
      )
      respond_to do |format|
        format.pdf { render pdf: "close_requests_#{@date}", layout: 'pdf.html' }
        format.html { render }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound do |exception|
    respond_to do |format|
      format.json do
        render json: 'not found', status: 404
      end
    end
  end

  protected

  def configure_permitted_parameters
   # Permit the `subscribe_newsletter` parameter along with the other
   # sign up parameters.
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :json

  def create
    comment = CommentCreator.new(
      user: current_user,
      request_id: params[:request_id],
      comment_params: comment_params
    ).call

    if comment.valid?
      render(
        json: comment.to_json(
          include: [
            :user,
            request: { include: :user }
          ]
        ),
        status: :created,
        location: @user
      )
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  def index
    request = Request.find(params[:request_id])
    render(
      json: request.comments
                   .includes(:user)
                   .order(created_at: :desc)
                   .to_json(include: :user)
    )
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  respond_to :json, :html

  def index
    requests = current_user.requests.includes(:user).order(updated_at: :desc)
    render json: requests.to_json(include: :user)
  end

  def create
    request = current_user.requests.build(request_params)
    request.save
    respond_with(request)
  end

  def resolve
    request = current_user.requests.find(params[:id])
    request.resolve!

    render json: request.to_json(include: :user)
  end

  private

  def request_params
    params.require(:request).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/show.html.erb
<%= react_component('App') %>
<script type="text/javascript">
  window.globalState = {}
  window.paths = {
    requests: '<%= admin_requests_path %>'
  }
  window.enableNewRequest = false;
  window.enableRequestReport = true;
</script>

app/views/admin/requests/_report.html.erb
<div class="row">
  <div class="col-xs-6">
    <h3>Closed requests in <%= @date %></h3>
    <p>From <%= l(@initial_date, format: :date) %> to <%= l(@final_date, format: :date) %></p>
  </div>
</div>
<div class="row">
  <table class="table table-striped">
    <thead>
      <th>Id</th>
      <th>Title</th>
      <th>Created at</th>
      <th>Updated at</th>
    </thead>
    <tbody>
      <% @closed_requests.each do |request| %>
        <tr>
          <td><%= request.id %></td>
          <td><%= request.title %></td>
          <td><%= l(request.created_at, format: :short) %></td>
          <td><%= l(request.updated_at, format: :short) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/requests/report.html.erb
<ol class="breadcrumb">
  <li>
    <a href="/admin">Home</a>
  </li>
  <li class="active">Reports</li>
</ol>
<a href="/admin/requests/report.pdf" target="_blank">Export to PDF</a>

<%= render partial: 'report.html' %>

app/views/admin/requests/report.pdf.erb
<%= render partial: 'report.html' %>

app/views/home/show.html.erb
<%= react_component('App') %>
<script type="text/javascript">
  window.globalState = {}
  window.paths = {
    requests: '<%= requests_path %>'
  }
  window.enableNewRequest = true;
  window.enableRequestReport = false;
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SupportApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Support Admin Area</a>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><%= link_to(t(:logout), destroy_user_session_path, method: :delete) %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SupportApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SupportApp</a>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><%= link_to(t(:logout), destroy_user_session_path, method: :delete) %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head></head>
  <title>SupportApp</title>
  <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
  <%= wicked_pdf_javascript_include_tag "application" %>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>